# Generated by Django 5.2.7 on 2025-10-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incidents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_type", models.CharField(max_length=100)),
                (
                    "incident_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.remoteserverstatus",
                    ),
                ),
            ],
        ),
    ]
