# Generated by Django 5.2.7 on 2025-10-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RemoteServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField(help_text='CPU usage in percent')),
                ('mem', models.IntegerField(help_text='Memory usage in percent')),
                ('disk', models.IntegerField(help_text='Disk usage in percent')),
                ('uptime', models.DurationField(help_text='Uptime')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='data_collection.remoteserver')),
            ],
        ),
    ]
